PROGRAM MAT_SQUARE

IMPLICIT NONE
INTEGER I,J,K,N,NUM_IT
INTEGER T1,T2, CLOCK_RATE, CLOCK_MAX
INTEGER, PARAMETER :: OUT_UNIT = 20
PARAMETER (NUM_IT = 500)
REAL, DIMENSION (NUM_IT) :: TIMES
REAL, DIMENSION (:,:), ALLOCATABLE :: A, B, C

DO I = 1,NUM_IT

ALLOCATE(A(I,I), B(I,I))
B = 0.

IF (I==1) THEN
  A(1,1) = 1
ELSE
  A(1:I-1,1:I-1) = C(1:I-1,1:I-1)
  DEALLOCATE(C)
  DO J = I-1,I
    DO K = I-1,I
      A(J,K) = J * K
    END DO 
  END DO
END IF  
  
CALL SYSTEM_CLOCK ( T1 , CLOCK_RATE, CLOCK_MAX )  
B = MATMUL(A,A)
CALL SYSTEM_CLOCK ( T2 , CLOCK_RATE, CLOCK_MAX )
TIMES(I) = REAL(T2 - T1)/REAL(CLOCK_RATE)

ALLOCATE(C(I,I))
C = A

DEALLOCATE(A,B)

END DO

OPEN ( UNIT = OUT_UNIT, FILE = "/home/nick/Documents/results.txt", ACTION = "WRITE", STATUS = "REPLACE" )
DO N = 1, NUM_IT
  WRITE (OUT_UNIT,*) TIMES(N)
END DO

PRINT 100, TIMES
100 FORMAT(F10.8)

END
